# Generated by Django 5.0.7 on 2024-07-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.CharField(max_length=2),
        ),
    ]
