# Generated by Django 5.0.7 on 2024-08-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_video_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_link',
            field=models.TextField(),
        ),
    ]
